targets:
  $default:
    builders:
      sass_builder|sass_builder:
        enabled: True
        generate_for: ["web/styles.scss", "lib/**.scss", "lib/src/files/files_component.scss"]
      build_web_compilers|entrypoint:
        release_options:
         dart2js_args:
           - -DPRODUCTION=true
           - -DAPI_URL=localhost:8081
