name: DiscordFileStorage
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.2
  angular_router: ^2.0.0
  js: ^0.6.2

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.10.9
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.0
  test: ^1.6.3
  sass_builder: ^2.1.3
